name: Sample Site Validation

on:
  pull_request:

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    
    env:
     Codeql.Enabled: true
     
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Sreenivas-Kalluru/Perform-Dynamic-PR.git
          ref: main # or the branch you want to work   with
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Sync Meta data Information 
        run: Scripts/syncMetadata.sh

      - name: Create and Push File
        run: |
          git config --local user.email "69580789+Sreenivas-Kalluru@users.noreply.github.com"
          git config --local user.name "Sreenivas-Kalluru"
          git add  Scripts/commit.txt
          git commit -m 'Data Updated' ||  echo 'No changes to commit'
          git fetch origin main
          git push origin HEAD:main || echo "Error occurred while push to origin"

      - name: Check for differences
        run: |
          if ! git diff --quiet; then
            echo "::error ::Detected changes when regenerating website."
            git diff --stat
            exit 1
          fi

